backend:
  name: github
  repo: beaudavenport/gatsby-celestial-loom

media_folder: static/assets
public_folder: assets
site_url: https://boring-einstein-e60f31.netlify.com

collections:
  - name: blog
    label: Blog
    folder: data/blog
    preview_path: 'blog/{{slug}}'
    create: true
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'blogTemplate'}
      - { name: 'type', label: 'type', widget: 'hidden', default: 'blog'}
      - { name: path, label: Path }
      - { name: 'publishDate', label: 'Publish Date', widget: 'date' }
      - { name: title, label: Title }
      - { name: 'image', label: 'Image', widget: 'image' }
      - { name: body, label: Body, widget: markdown }

  - name: 'events'
    label: 'Events'
    folder: data/events
    preview_path: 'events/{{slug}}'
    create: true
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'eventTemplate'}
      - { name: 'type', label: 'type', widget: 'hidden', default: 'events'}
      - { name: 'path', label: 'Path' }
      - { name: 'eventDate', label: 'Event Date', widget: 'date' }
      - { name: 'image', label: 'Image', widget: 'image' }
      - { name: 'title', label: 'Title' }
      - { name: 'location', label: 'Name of Venue' }
      - { name: 'mapsLink', label: 'Google Maps Link' }
      - { name: 'eventPrice', label: 'Price (increments of $5.00)', widget: 'number', default: '3', min: 0, valueType: 'float', step: 5.00 }
      - { name: 'publishDate', label: 'Publish Date', widget: 'date' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'services'
    label: 'Services'
    folder: data/services
    preview_path: 'services/{{slug}}'
    create: true
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'serviceTemplate'}
      - { name: 'type', label: 'type', widget: 'hidden', default: 'services'}
      - { name: 'title', label: 'Title' }
      - { name: 'origin', label: 'Origin', widget: 'select', options: ['Western', 'Vedic', 'Celtic', 'Native American']}
      - { name: 'price', label: 'Price (increments of $5.00)', widget: 'number', default: '3', min: 0, valueType: 'float', step: 5.00 }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'signs'
    label: 'Signs'
    folder: data/signs
    preview_path: 'signs/{{slug}}'
    create: true
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'toolboxTemplate'}
      - { name: 'type', label: 'type', widget: 'hidden', default: 'signs'}
      - { name: 'title', label: 'Title' }
      - { name: 'icon', label: 'Icon' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'planets'
    label: 'Planets'
    folder: data/planets
    preview_path: 'planets/{{slug}}'
    create: true
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'toolboxTemplate'}
      - { name: 'type', label: 'type', widget: 'hidden', default: 'planets'}
      - { name: 'title', label: 'Title' }
      - { name: 'icon', label: 'Icon' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'houses'
    label: 'Houses'
    folder: data/houses
    preview_path: 'houses/{{slug}}'
    create: true
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'toolboxTemplate'}
      - { name: 'type', label: 'type', widget: 'hidden', default: 'houses'}
      - { name: 'title', label: 'Title' }
      - { name: 'icon', label: 'Icon' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
